twitter:
  consumer:
    key: lRl3PmfKX8S6AxvAnidRPYNVA
    secret: whhZKj6ujcTfCMXOVsx6hhc1jahqPqJeYSWvhxmfG7DOJ1n30H
  access:
    token: 1470512602216382466-Ex4aoi2nW1kjctCNejrEZRNuPL1TBy
    secret: AE2NRZCr0AGuIKD3RUD0Oxs6DHUUSqjwLtlEXzXyzyoIJ

  consumer_post:
    key: lRl3PmfKX8S6AxvAnidRPYNVA
    secret: whhZKj6ujcTfCMXOVsx6hhc1jahqPqJeYSWvhxmfG7DOJ1n30H


niche:
  saas:
    names :    chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio ,

