twitter:
  consumer:
    key: lL8eC7cTpzbTxnzYEzrYJxOLs
    secret: KKPVXzKO65abSSQ8fGbaXOUcss3ghAbJXmg63aO4noGeyqehZf
  access:
    token: 1470512602216382466-YRaljMRIBBxQUVrHzAux94o7psAYuo
    secret: JQSZNcyQtq2TRtrTqOSCBmq8CL7o40IFaS4RasezU7LBr

  consumer_post:
    key: lL8eC7cTpzbTxnzYEzrYJxOLs
    secret: KKPVXzKO65abSSQ8fGbaXOUcss3ghAbJXmg63aO4noGeyqehZf


niche:
  saas:
    names : POPSUGARFitness ,  lovesweatandfit , runnersworld , FitMenCook , roanwar

