twitter:
  consumer:
    key: U9SmSPhyUj36tPHVYWji7Fihx
    secret: RqWGDwXbRb5WFbHFg0c2TXod9xWOTD3M7IgQRhJqJgQ9FSvQWL
  access:
    token: 1470512602216382466-SxYanhnkdQS3iG6Vh51M1neyqwCopa
    secret: 43QkR3a5mSX8nZcAjqRciHvOB30touVEKUwAjWYvRkicA


  consumer_post:
    key: U9SmSPhyUj36tPHVYWji7Fihx
    secret: RqWGDwXbRb5WFbHFg0c2TXod9xWOTD3M7IgQRhJqJgQ9FSvQWL


niche:
  saas:
    names : PerfectGuide_,limitlessmindon,LifeNotesLN,BrainiacLab,SeekMastery,Risk2Earn,ShreyaPattar


people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen

