twitter:
  consumer:
    key: ebYyUNb1gN7YheKaFHw551RlT
    secret: EXZgyeFUwhOLuJrHDtWDBQAlySe8yeaIIioLfoj9j0AFJFHEUq
  access:
    token: 1470512602216382466-WPrAqJ8ILG0mrT85U4opTwJhRD5WLw
    secret: RLvVbmE1jIEgGnqYlzZznekjMZpfsQ2IBiu7EtdKbJih0

  consumer_post:
    key: ebYyUNb1gN7YheKaFHw551RlT
    secret: EXZgyeFUwhOLuJrHDtWDBQAlySe8yeaIIioLfoj9j0AFJFHEUq


niche:
  saas:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio ,

