twitter:
  consumer:
    key: 4MwPkgHxvlH3djJlWeUpxqDj1
    secret: qx6HMcZjce84eRKd9LcPlZASv1wlYLNprb3iQZhJTuCYcoXpHm
  access:
    token: 1470512602216382466-a8ylY2tggHRf9sCUQHpxNOnuYh4bi3
    secret: Lq6MrQKtMqDiPgMhK8HfxfzJJJAk5I9QvK8laAjmxFxfm

  consumer_post:
    key: 4MwPkgHxvlH3djJlWeUpxqDj1
    secret: qx6HMcZjce84eRKd9LcPlZASv1wlYLNprb3iQZhJTuCYcoXpHm


niche:
  saas:
    names : POPSUGARFitness ,  lovesweatandfit , runnersworld , FitMenCook , roanwar

