twitter:
  consumer:
    key: WFqFu2pSbnOY7cs0iA82U8WGx
    secret: QSi8W2lJfzRnR9KxLou8XQ4ZnPgo2Sn3xuHULvAE5FB5sPG12n
  access:
    token: 1470512602216382466-9HRj4v1SaiYXVFlxvTPZ1mh5aLZhQx
    secret: BQNe0BRjXgf22ojUGckAQLLThnFPwQ8ZFii58RaKxARU9

  consumer_post:
    key: WFqFu2pSbnOY7cs0iA82U8WGx
    secret: QSi8W2lJfzRnR9KxLou8XQ4ZnPgo2Sn3xuHULvAE5FB5sPG12n

niche:
  saas:
    names : dennishegstad,jasonlk,andrewchen,ttunguz,firstround,mwseibel,NathanLatka,iamwillcannon,ImSamThompson,iuditg,upadhyay_harsh1,TheCoolestCool

people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen

