twitter:
  consumer:
    key: AUNK6UuTmPQVNCMZYz8zA62WO
    secret: zeF5IJqytiNPAW1W0Qz2bMLJjvhMkHbiw6pZQCjDDIHxa45FEC
  access:
    token: 1470512602216382466-EoKuwosILJ9bsYm95poWZvcD47WvZ0
    secret: WApxuONJsEcvk86qwsHiRmtge6FqL7UloVDqn334HkO5G

  consumer_post:
    key: AUNK6UuTmPQVNCMZYz8zA62WO
    secret: zeF5IJqytiNPAW1W0Qz2bMLJjvhMkHbiw6pZQCjDDIHxa45FEC

niche:
  saas:
    names : dennishegstad,jasonlk,andrewchen,ttunguz,firstround,mwseibel,NathanLatka,iamwillcannon,ImSamThompson,iuditg,upadhyay_harsh1,TheCoolestCool

people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen
