twitter:
  consumer:
    key: 7Ply7vKkntvCXWrPJbYcJ3GoV
    secret: N1ZY9mFQ2KV37dZI6018cq4BopoXkOtvE9PKdzOBdH6FPpS4Ln
  access:
    token: 1470512602216382466-XH959tAFzMts39wgmANilXX7H0zLbq
    secret: zbemHM93Ycd9Xicz3myM44oRC8FyxU6p0WhLtm0p6xO91


  consumer_post:
    key: 7Ply7vKkntvCXWrPJbYcJ3GoV
    secret: N1ZY9mFQ2KV37dZI6018cq4BopoXkOtvE9PKdzOBdH6FPpS4Ln


niche:
  saas:
    names : PerfectGuide_,limitlessmindon,LifeNotesLN,BrainiacLab,SeekMastery,Risk2Earn,ShreyaPattar


people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen

