twitter:
  consumer:
    key: 8U7mSPWWbmCQMtPcxJSYh5NdC
    secret: isG8VxmNuvBBLkAEmkoPzms4ZO7ujXHn6LJmsQJPnsHfo22JcL
  access:
    token: 1470512602216382466-ZYllfBVgA4UucPN4lnoxB5seWBpJgn
    secret: O1qYdwqOQD7ODEYkQMtJ9Nb1oNTU2909q91JIQ8NQvTyB

  consumer_post:
    key: 8U7mSPWWbmCQMtPcxJSYh5NdC
    secret: isG8VxmNuvBBLkAEmkoPzms4ZO7ujXHn6LJmsQJPnsHfo22JcL

niche:
  saas:
    names : dennishegstad,jasonlk,andrewchen,ttunguz,firstround,mwseibel,NathanLatka,iamwillcannon,ImSamThompson,iuditg,upadhyay_harsh1,TheCoolestCool

people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen

