twitter:
  consumer:
    key: a6O8gWvSHOaFyzVE6BKYxmgZf
    secret: 92zxSI35Y5hYeWju8QvQbpxky40eWv4FKJAfoYKhYlEN10OS7v
  access:
    token: 1470512602216382466-qp5l8I5PnN8AffWw91LTsZTsiXJMI2
    secret: 8FQHuSyOInBkzZvREjxRFYbxbI5v3QFFm2VoIzKxLuRBc

  consumer_post:
    key: a6O8gWvSHOaFyzVE6BKYxmgZf
    secret: 92zxSI35Y5hYeWju8QvQbpxky40eWv4FKJAfoYKhYlEN10OS7v

niche:
  saas:
    names : dennishegstad,jasonlk,andrewchen,ttunguz,firstround,mwseibel,NathanLatka,iamwillcannon,ImSamThompson,iuditg,upadhyay_harsh1,TheCoolestCool

people:
  engage:
    names :   agazdecki ,  chddaniel  ,  ChanningAllen  ,  mkhundmiri   ,  levelsio, linuz90 , ShaanVP , noahwbragg,KennethCassel , MakadiaHarsh , dr , dagorenouf , thisiskp_ , damengchen

